//
// Created by 毛维义 on 2021/9/25.
//

#ifndef FFPLAYER_UTIL_H
#define FFPLAYER_UTIL_H

#define FFMPEG_ERR_OPEN_INPUT 1
#define FFMPEG_ERR_FIND_STREAM_INFO 2
#define FFMPEG_ERR_CODEC_PARAMS_TO_CONTEXT 3
#define FFMPEG_ERR_CODEC_OPEN 4
#define FFMPEG_ERR_NOT_AUDIO_VIDEO_STREAM 5

class Util {

};


#endif //FFPLAYER_UTIL_H
